#!/usr/bin/env -S node --test --test-reporter=spec

const readerTests = require('../tests/parse');
const writerTests = require('../tests/stringify');
const lib = require('../src/main');

const tests = [...Object.values(readerTests), ...Object.values(writerTests)];

tests.forEach(func => {
    func(lib);
});
